# uncaughtException
> Node.js 原生提供 uncaughtException 事件挂到 process 对象上，用于捕获所有未处理的异常：
> 一旦 uncaughtException 事件触发，整个 node 进程将 crash 掉，如果不做一些善后处理的话会导致整个服务挂掉，这对于线上的服务来说将是非常不好的。
```js
//捕获同步和异步错误
process.on('uncaughtException', (err) => {
    console.error('Error caught in uncaughtException event:', err);
});
//捕获Promise没有catch处理的reject
process.on('unhandledRejection', (reason, p) => {
});
```
- 当异常出现时，直接从对应执行栈中断，而到process捕获的异常事件下，导致了v8引擎的垃圾回收功能不能按照正常流程工作，然后开始出现内存泄漏问题。


# domain模块，废弃
- domin明显的优点，能把出问题时的一些信息传递给错误处理函数，可以做一些打点上报等处理工作，最起码保证重启后的服务，
- 比如当服务出错的时候，可以把用户请求栈信息传给下游，返回告知用户服务异常，而不是用户一直等到请求自动超时。
- 很难去保证不造成内存的泄漏。

# 多进程模式加异常捕获后重启
